import type {
  AdFieldDefinition,
  AdPlacementDefinition,
  AdvertiserAd,
  AdvertiserAdSettings,
  AdPlacementId,
  AdvertiserAdPlatformSettings,
} from '@/types/advertiser-ads';

const ISO = new Date().toISOString();

export const DEFAULT_AD_FIELD_DEFINITIONS: AdFieldDefinition[] = [
  {
    id: 'field-fabric',
    key: 'fabricTypes',
    labelAr: 'أنواع القماش',
    labelEn: 'Fabric types',
    type: 'multiselect',
    options: [
      { value: 'cotton', labelAr: 'قطن', labelEn: 'Cotton' },
      { value: 'polyester', labelAr: 'بوليستر', labelEn: 'Polyester' },
      { value: 'silk', labelAr: 'حرير', labelEn: 'Silk' },
      { value: 'wool', labelAr: 'صوف', labelEn: 'Wool' },
      { value: 'linen', labelAr: 'كتان', labelEn: 'Linen' },
      { value: 'denim', labelAr: 'دنيم', labelEn: 'Denim' },
    ],
    required: false,
    enabled: true,
    order: 1,
  },
  {
    id: 'field-colors',
    key: 'colors',
    labelAr: 'ألوان البسة',
    labelEn: 'Clothing colors',
    type: 'multiselect',
    options: [
      { value: 'black', labelAr: 'أسود', labelEn: 'Black' },
      { value: 'white', labelAr: 'أبيض', labelEn: 'White' },
      { value: 'red', labelAr: 'أحمر', labelEn: 'Red' },
      { value: 'blue', labelAr: 'أزرق', labelEn: 'Blue' },
      { value: 'green', labelAr: 'أخضر', labelEn: 'Green' },
      { value: 'beige', labelAr: 'بيج', labelEn: 'Beige' },
    ],
    required: false,
    enabled: true,
    order: 2,
  },
  {
    id: 'field-sizes',
    key: 'sizes',
    labelAr: 'المقاسات',
    labelEn: 'Sizes',
    type: 'multiselect',
    options: [
      { value: 'xs', labelAr: 'XS', labelEn: 'XS' },
      { value: 's', labelAr: 'S', labelEn: 'S' },
      { value: 'm', labelAr: 'M', labelEn: 'M' },
      { value: 'l', labelAr: 'L', labelEn: 'L' },
      { value: 'xl', labelAr: 'XL', labelEn: 'XL' },
      { value: 'xxl', labelAr: 'XXL', labelEn: 'XXL' },
    ],
    required: true,
    enabled: true,
    order: 3,
  },
  {
    id: 'field-stock',
    key: 'stockRemaining',
    labelAr: 'العدد المتبقي',
    labelEn: 'Stock remaining',
    type: 'number',
    required: true,
    enabled: true,
    order: 4,
  },
  {
    id: 'field-price',
    key: 'price',
    labelAr: 'السعر',
    labelEn: 'Price',
    type: 'price',
    required: true,
    enabled: true,
    order: 5,
  },
  {
    id: 'field-phone',
    key: 'phone',
    labelAr: 'رقم الهاتف',
    labelEn: 'Phone number',
    type: 'phone',
    required: false,
    enabled: true,
    order: 6,
  },
  {
    id: 'field-whatsapp',
    key: 'whatsapp',
    labelAr: 'واتساب أو رابط واتساب',
    labelEn: 'WhatsApp or WhatsApp link',
    type: 'whatsapp',
    required: true,
    enabled: true,
    order: 7,
  },
  {
    id: 'field-discount',
    key: 'discountPercent',
    labelAr: 'نسبة الحسم',
    labelEn: 'Discount %',
    type: 'percent',
    required: false,
    enabled: true,
    order: 8,
  },
  {
    id: 'field-shipping',
    key: 'shipping',
    labelAr: 'الشحن',
    labelEn: 'Shipping',
    type: 'select',
    options: [
      { value: 'free', labelAr: 'شحن مجاني', labelEn: 'Free shipping' },
      { value: 'paid', labelAr: 'شحن مدفوع', labelEn: 'Paid shipping' },
      { value: 'pickup', labelAr: 'استلام من المتجر', labelEn: 'Store pickup' },
    ],
    required: true,
    enabled: true,
    order: 9,
  },
];

export const DEFAULT_AD_PLACEMENTS: AdPlacementDefinition[] = [
  {
    id: 'home_hero_strip',
    labelAr: 'شريط أعلى الصفحة الرئيسية',
    labelEn: 'Home — top strip',
    descriptionAr: 'بانر أفقي بارز فوق المحتوى في الصفحة الرئيسية',
    descriptionEn: 'Prominent horizontal strip on the homepage',
    pricePerDay: 25,
    enabled: true,
    maxSlots: 3,
  },
  {
    id: 'home_featured_grid',
    labelAr: 'شبكة مميزة — الرئيسية',
    labelEn: 'Home — featured grid',
    descriptionAr: 'بطاقات إعلانات ضمن قسم مميز في الصفحة الرئيسية',
    descriptionEn: 'Ad cards in a featured section on the homepage',
    pricePerDay: 15,
    enabled: true,
    maxSlots: 6,
  },
  {
    id: 'search_top',
    labelAr: 'أعلى صفحة البحث',
    labelEn: 'Search — top banner',
    descriptionAr: 'يظهر قبل نتائج البحث عن العقارات',
    descriptionEn: 'Shown above property search results',
    pricePerDay: 12,
    enabled: true,
    maxSlots: 2,
  },
  {
    id: 'search_sidebar',
    labelAr: 'الشريط الجانبي — البحث',
    labelEn: 'Search — sidebar',
    descriptionAr: 'عمود جانبي في صفحة البحث (شاشات كبيرة)',
    descriptionEn: 'Sidebar column on search (large screens)',
    pricePerDay: 8,
    enabled: true,
    maxSlots: 4,
  },
  {
    id: 'property_detail_sidebar',
    labelAr: 'تفاصيل العقار — جانبي',
    labelEn: 'Property detail — sidebar',
    descriptionAr: 'بجانب معلومات العقار عند عرض التفاصيل',
    descriptionEn: 'Next to property details page',
    pricePerDay: 10,
    enabled: true,
    maxSlots: 3,
  },
  {
    id: 'agents_page_banner',
    labelAr: 'صفحة الوكلاء',
    labelEn: 'Agents page banner',
    descriptionAr: 'بانر في أعلى صفحة الوكلاء',
    descriptionEn: 'Banner at top of agents directory',
    pricePerDay: 9,
    enabled: true,
    maxSlots: 2,
  },
];

export const DEFAULT_PLATFORM_SETTINGS: AdvertiserAdPlatformSettings = {
  requirePaymentBeforeReview: true,
  autoExpireEnabled: true,
  allowAdvertiserEditPending: true,
  defaultDurationDays: 14,
  maxImages: 5,
  featureOnApprove: false,
};

export const DEFAULT_AD_SETTINGS: AdvertiserAdSettings = {
  fields: DEFAULT_AD_FIELD_DEFINITIONS,
  placements: DEFAULT_AD_PLACEMENTS,
  platform: DEFAULT_PLATFORM_SETTINGS,
  defaultCategoryKey: 'clothing',
  defaultCategoryLabelAr: 'ملابس وأزياء',
  defaultCategoryLabelEn: 'Clothing & fashion',
};

export const AD_DURATION_OPTIONS = [7, 14, 30] as const;

export function getPlacementById(
  settings: AdvertiserAdSettings,
  id: AdPlacementId,
): AdPlacementDefinition | undefined {
  return settings.placements.find((p) => p.id === id && p.enabled);
}

export function calcAdTotal(pricePerDay: number, durationDays: number): number {
  return Math.round(pricePerDay * durationDays * 100) / 100;
}

export function placementLabel(
  placement: AdPlacementDefinition,
  isAr: boolean,
): string {
  return isAr ? placement.labelAr : placement.labelEn;
}

export function fieldLabel(field: AdFieldDefinition, isAr: boolean): string {
  return isAr ? field.labelAr : field.labelEn;
}

export function enabledFields(settings: AdvertiserAdSettings): AdFieldDefinition[] {
  return [...settings.fields]
    .filter((f) => f.enabled)
    .sort((a, b) => a.order - b.order);
}

function demoBase(
  partial: Omit<
    AdvertiserAd,
    'adminNotes' | 'isFeatured' | 'priority' | 'clicks' | 'videoUrl'
  > &
    Partial<
      Pick<
        AdvertiserAd,
        'adminNotes' | 'isFeatured' | 'priority' | 'clicks' | 'videoUrl'
      >
    >,
): AdvertiserAd {
  return {
    adminNotes: null,
    isFeatured: false,
    priority: 0,
    clicks: 0,
    videoUrl: null,
    ...partial,
  };
}

const daysFromNow = (days: number) =>
  new Date(Date.now() + days * 86400000).toISOString();

/** Demo ads across statuses & placements for admin + public UI */
export const DEMO_APPROVED_ADS: AdvertiserAd[] = [
  demoBase({
    id: 'demo-ad-clothing-1',
    advertiserId: 'demo-advertiser',
    advertiserName: 'بوتيك الأناقة',
    advertiserEmail: 'boutique@example.com',
    categoryKey: 'clothing',
    title: 'تشكيلة صيفية — خصم 20%',
    description: 'أقمشة قطنية فاخرة بمقاسات S إلى XXL. شحن مجاني داخل المدينة.',
    images: [
      'https://images.unsplash.com/photo-1445205170230-053b83016050?w=800&q=80&auto=format&fit=crop',
    ],
    placementId: 'home_featured_grid',
    durationDays: 14,
    pricePerDay: 15,
    totalAmount: 210,
    amountPaid: 210,
    isPaid: true,
    status: 'approved',
    rejectionReason: null,
    isFeatured: true,
    priority: 10,
    fields: {
      fabricTypes: ['cotton', 'linen'],
      colors: ['white', 'beige'],
      sizes: ['s', 'm', 'l'],
      stockRemaining: 48,
      price: 89,
      phone: '+963993153333',
      whatsapp: '+963993153333',
      discountPercent: 20,
      shipping: 'free',
    },
    startsAt: ISO,
    expiresAt: daysFromNow(14),
    views: 124,
    clicks: 18,
    createdAt: ISO,
    updatedAt: ISO,
  }),
  demoBase({
    id: 'demo-ad-clothing-strip',
    advertiserId: 'demo-advertiser',
    advertiserName: 'بوتيك الأناقة',
    advertiserEmail: 'boutique@example.com',
    categoryKey: 'clothing',
    title: 'عرض محدود — توصيل سريع عبر واتساب',
    description: null,
    images: [
      'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=800&q=80&auto=format&fit=crop',
    ],
    placementId: 'home_hero_strip',
    durationDays: 7,
    pricePerDay: 25,
    totalAmount: 175,
    amountPaid: 175,
    isPaid: true,
    status: 'approved',
    rejectionReason: null,
    isFeatured: true,
    priority: 8,
    fields: {
      whatsapp: '+963993153333',
      price: 120,
      discountPercent: 15,
      shipping: 'free',
      sizes: ['s', 'm', 'l'],
      stockRemaining: 30,
    },
    startsAt: ISO,
    expiresAt: daysFromNow(7),
    views: 56,
    clicks: 9,
    createdAt: ISO,
    updatedAt: ISO,
  }),
  demoBase({
    id: 'demo-ad-clothing-video',
    advertiserId: 'demo-advertiser-7',
    advertiserName: 'مودا لاين',
    advertiserEmail: 'moda@example.com',
    categoryKey: 'clothing',
    title: 'عرض فيديو — تشكيلة الخريف',
    description:
      'إعلان فيديو تجريبي بعد موافقة الإدارة، يظهر في صفحة الإعلانات وأماكن الظهور المختارة.',
    images: [
      'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800&q=80&auto=format&fit=crop',
    ],
    videoUrl:
      'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    placementId: 'home_featured_grid',
    durationDays: 14,
    pricePerDay: 15,
    totalAmount: 210,
    amountPaid: 210,
    isPaid: true,
    status: 'approved',
    rejectionReason: null,
    isFeatured: true,
    priority: 9,
    fields: {
      fabricTypes: ['wool', 'cotton'],
      colors: ['beige', 'black'],
      sizes: ['s', 'm', 'l'],
      stockRemaining: 24,
      price: 145,
      phone: '+963993153333',
      whatsapp: '+963993153333',
      discountPercent: 18,
      shipping: 'free',
    },
    startsAt: ISO,
    expiresAt: daysFromNow(14),
    views: 84,
    clicks: 12,
    createdAt: ISO,
    updatedAt: ISO,
  }),
  demoBase({
    id: 'demo-ad-denim-grid',
    advertiserId: 'demo-advertiser-4',
    advertiserName: 'ستايل دينيم',
    advertiserEmail: 'denim@example.com',
    categoryKey: 'clothing',
    title: 'جينز كلاسيك — خصم 30%',
    description: 'تشكيلة دنيم رجالي ونسائي بألوان متعددة ومقاسات واسعة.',
    images: [
      'https://images.unsplash.com/photo-1542272604-787c3835535d?w=800&q=80&auto=format&fit=crop',
    ],
    placementId: 'home_featured_grid',
    durationDays: 14,
    pricePerDay: 15,
    totalAmount: 210,
    amountPaid: 210,
    isPaid: true,
    status: 'approved',
    rejectionReason: null,
    isFeatured: true,
    priority: 7,
    fields: {
      fabricTypes: ['denim'],
      colors: ['blue', 'black'],
      sizes: ['s', 'm', 'l', 'xl'],
      stockRemaining: 65,
      price: 65,
      phone: '+963993153333',
      whatsapp: '+963993153333',
      discountPercent: 30,
      shipping: 'free',
    },
    startsAt: ISO,
    expiresAt: daysFromNow(12),
    views: 310,
    clicks: 42,
    createdAt: ISO,
    updatedAt: ISO,
  }),
  demoBase({
    id: 'demo-ad-silk-grid',
    advertiserId: 'demo-advertiser-5',
    advertiserName: 'حرير الشام',
    advertiserEmail: 'silk@example.com',
    categoryKey: 'clothing',
    title: 'بلوزات حرير فاخرة',
    description: 'قطع محدودة من الحرير الطبيعي — استلام من المتجر أو شحن مدفوع.',
    images: [
      'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=800&q=80&auto=format&fit=crop',
    ],
    placementId: 'home_featured_grid',
    durationDays: 30,
    pricePerDay: 15,
    totalAmount: 450,
    amountPaid: 450,
    isPaid: true,
    status: 'approved',
    rejectionReason: null,
    priority: 5,
    fields: {
      fabricTypes: ['silk'],
      colors: ['red', 'beige', 'black'],
      sizes: ['xs', 's', 'm'],
      stockRemaining: 18,
      price: 185,
      whatsapp: '+963993153333',
      discountPercent: 5,
      shipping: 'paid',
    },
    startsAt: ISO,
    expiresAt: daysFromNow(25),
    views: 88,
    clicks: 11,
    createdAt: ISO,
    updatedAt: ISO,
  }),
  demoBase({
    id: 'demo-ad-kids-grid',
    advertiserId: 'demo-advertiser-6',
    advertiserName: 'عالم الأطفال',
    advertiserEmail: 'kids@example.com',
    categoryKey: 'clothing',
    title: 'ملابس أطفال قطنية',
    description: 'راحة يومية للأطفال — قطن 100% وألوان مبهجة.',
    images: [
      'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?w=800&q=80&auto=format&fit=crop',
    ],
    placementId: 'home_featured_grid',
    durationDays: 14,
    pricePerDay: 15,
    totalAmount: 210,
    amountPaid: 210,
    isPaid: true,
    status: 'approved',
    rejectionReason: null,
    fields: {
      fabricTypes: ['cotton'],
      colors: ['green', 'white', 'blue'],
      sizes: ['xs', 's', 'm'],
      stockRemaining: 90,
      price: 35,
      whatsapp: '+963993153333',
      discountPercent: 12,
      shipping: 'free',
    },
    startsAt: ISO,
    expiresAt: daysFromNow(14),
    views: 205,
    clicks: 27,
    createdAt: ISO,
    updatedAt: ISO,
  }),
  demoBase({
    id: 'demo-ad-search-banner',
    advertiserId: 'demo-advertiser-4',
    advertiserName: 'ستايل دينيم',
    advertiserEmail: 'denim@example.com',
    categoryKey: 'clothing',
    title: 'عروض البحث — جاكيتات خفيفة',
    description: 'بانر أعلى نتائج البحث: جاكيتات ربيع/صيف بأسعار تنافسية.',
    images: [
      'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800&q=80&auto=format&fit=crop',
    ],
    placementId: 'search_top',
    durationDays: 7,
    pricePerDay: 12,
    totalAmount: 84,
    amountPaid: 84,
    isPaid: true,
    status: 'approved',
    rejectionReason: null,
    isFeatured: true,
    priority: 6,
    fields: {
      fabricTypes: ['polyester', 'cotton'],
      colors: ['black', 'beige'],
      sizes: ['m', 'l', 'xl'],
      stockRemaining: 40,
      price: 95,
      whatsapp: '+963993153333',
      discountPercent: 18,
      shipping: 'free',
    },
    startsAt: ISO,
    expiresAt: daysFromNow(6),
    views: 142,
    clicks: 21,
    createdAt: ISO,
    updatedAt: ISO,
  }),
  demoBase({
    id: 'demo-ad-search-sidebar',
    advertiserId: 'demo-advertiser-5',
    advertiserName: 'حرير الشام',
    advertiserEmail: 'silk@example.com',
    categoryKey: 'clothing',
    title: 'إكسسوارات ووشاحات حرير',
    description: 'يظهر في الشريط الجانبي لصفحة البحث.',
    images: [
      'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=800&q=80&auto=format&fit=crop',
    ],
    placementId: 'search_sidebar',
    durationDays: 14,
    pricePerDay: 8,
    totalAmount: 112,
    amountPaid: 112,
    isPaid: true,
    status: 'approved',
    rejectionReason: null,
    fields: {
      fabricTypes: ['silk'],
      colors: ['red', 'green'],
      sizes: ['s', 'm'],
      stockRemaining: 55,
      price: 45,
      whatsapp: '+963993153333',
      discountPercent: 8,
      shipping: 'paid',
    },
    startsAt: ISO,
    expiresAt: daysFromNow(11),
    views: 67,
    clicks: 8,
    createdAt: ISO,
    updatedAt: ISO,
  }),
  demoBase({
    id: 'demo-ad-property-sidebar',
    advertiserId: 'demo-advertiser',
    advertiserName: 'بوتيك الأناقة',
    advertiserEmail: 'boutique@example.com',
    categoryKey: 'clothing',
    title: 'إطلالة منزل أنيق — خصم خاص',
    description: 'إعلان جانبي بجانب تفاصيل العقار: ملابس منزلية مريحة.',
    images: [
      'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=800&q=80&auto=format&fit=crop',
    ],
    placementId: 'property_detail_sidebar',
    durationDays: 14,
    pricePerDay: 10,
    totalAmount: 140,
    amountPaid: 140,
    isPaid: true,
    status: 'approved',
    rejectionReason: null,
    priority: 4,
    fields: {
      fabricTypes: ['cotton'],
      colors: ['white', 'beige'],
      sizes: ['s', 'm', 'l', 'xl'],
      stockRemaining: 70,
      price: 55,
      phone: '+963993153333',
      whatsapp: '+963993153333',
      discountPercent: 25,
      shipping: 'free',
    },
    startsAt: ISO,
    expiresAt: daysFromNow(13),
    views: 98,
    clicks: 14,
    createdAt: ISO,
    updatedAt: ISO,
  }),
  demoBase({
    id: 'demo-ad-agents-banner',
    advertiserId: 'demo-advertiser-6',
    advertiserName: 'عالم الأطفال',
    advertiserEmail: 'kids@example.com',
    categoryKey: 'clothing',
    title: 'عرض الوكلاء — ملابس مدرسية',
    description: 'بانر أعلى صفحة الوكلاء لموسم العودة للمدرسة.',
    images: [
      'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=800&q=80&auto=format&fit=crop',
    ],
    placementId: 'agents_page_banner',
    durationDays: 14,
    pricePerDay: 9,
    totalAmount: 126,
    amountPaid: 126,
    isPaid: true,
    status: 'approved',
    rejectionReason: null,
    isFeatured: true,
    priority: 3,
    fields: {
      fabricTypes: ['cotton', 'polyester'],
      colors: ['blue', 'white'],
      sizes: ['xs', 's', 'm', 'l'],
      stockRemaining: 120,
      price: 42,
      whatsapp: '+963993153333',
      discountPercent: 15,
      shipping: 'free',
    },
    startsAt: ISO,
    expiresAt: daysFromNow(14),
    views: 73,
    clicks: 10,
    createdAt: ISO,
    updatedAt: ISO,
  }),
  demoBase({
    id: 'demo-ad-hero-strip-2',
    advertiserId: 'demo-advertiser-7',
    advertiserName: 'مودا لاين',
    advertiserEmail: 'moda@example.com',
    categoryKey: 'clothing',
    title: 'وصل حديثاً — مجموعة الخريف',
    description: 'شريط ثانٍ في أعلى الصفحة الرئيسية.',
    images: [
      'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800&q=80&auto=format&fit=crop',
    ],
    placementId: 'home_hero_strip',
    durationDays: 14,
    pricePerDay: 25,
    totalAmount: 350,
    amountPaid: 350,
    isPaid: true,
    status: 'approved',
    rejectionReason: null,
    priority: 2,
    fields: {
      fabricTypes: ['wool', 'cotton'],
      colors: ['beige', 'black'],
      sizes: ['s', 'm', 'l'],
      stockRemaining: 33,
      price: 140,
      whatsapp: '+963993153333',
      discountPercent: 10,
      shipping: 'paid',
    },
    startsAt: ISO,
    expiresAt: daysFromNow(14),
    views: 190,
    clicks: 25,
    createdAt: ISO,
    updatedAt: ISO,
  }),
  demoBase({
    id: 'demo-ad-pending-review',
    advertiserId: 'demo-advertiser-2',
    advertiserName: 'متجر النخبة',
    advertiserEmail: 'elite@example.com',
    categoryKey: 'clothing',
    title: 'جاكيتات شتوية رجالية',
    description: 'تشكيلة جديدة — بانتظار موافقة الإدارة',
    images: [
      'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&q=80&auto=format&fit=crop',
    ],
    placementId: 'search_top',
    durationDays: 14,
    pricePerDay: 12,
    totalAmount: 168,
    amountPaid: 168,
    isPaid: true,
    status: 'pending_review',
    rejectionReason: null,
    fields: {
      fabricTypes: ['wool'],
      colors: ['black', 'blue'],
      sizes: ['m', 'l', 'xl'],
      stockRemaining: 22,
      price: 150,
      whatsapp: '+963993153333',
      discountPercent: 10,
      shipping: 'paid',
    },
    startsAt: null,
    expiresAt: null,
    views: 0,
    createdAt: ISO,
    updatedAt: ISO,
  }),
  demoBase({
    id: 'demo-ad-pending-review-2',
    advertiserId: 'demo-advertiser-7',
    advertiserName: 'مودا لاين',
    advertiserEmail: 'moda@example.com',
    categoryKey: 'clothing',
    title: 'أحذية رياضية — طلب مراجعة',
    description: 'طلب إعلان جديد بانتظار موافقة الأدمن.',
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80&auto=format&fit=crop',
    ],
    placementId: 'home_featured_grid',
    durationDays: 14,
    pricePerDay: 15,
    totalAmount: 210,
    amountPaid: 210,
    isPaid: true,
    status: 'pending_review',
    rejectionReason: null,
    fields: {
      colors: ['red', 'black', 'white'],
      sizes: ['s', 'm', 'l', 'xl'],
      stockRemaining: 28,
      price: 110,
      whatsapp: '+963993153333',
      discountPercent: 20,
      shipping: 'free',
    },
    startsAt: null,
    expiresAt: null,
    views: 0,
    createdAt: ISO,
    updatedAt: ISO,
  }),
  demoBase({
    id: 'demo-ad-pending-pay',
    advertiserId: 'demo-advertiser-3',
    advertiserName: 'أزياء الشرق',
    advertiserEmail: 'east@example.com',
    categoryKey: 'clothing',
    title: 'فساتين سهرة',
    description: 'بانتظار إتمام الدفع',
    images: [
      'https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=800&q=80&auto=format&fit=crop',
    ],
    placementId: 'home_featured_grid',
    durationDays: 30,
    pricePerDay: 15,
    totalAmount: 450,
    amountPaid: 0,
    isPaid: false,
    status: 'pending_payment',
    rejectionReason: null,
    fields: {
      fabricTypes: ['silk', 'polyester'],
      colors: ['red', 'black'],
      sizes: ['s', 'm'],
      stockRemaining: 12,
      price: 220,
      whatsapp: '+963993153333',
      shipping: 'free',
    },
    startsAt: null,
    expiresAt: null,
    views: 0,
    createdAt: ISO,
    updatedAt: ISO,
  }),
  demoBase({
    id: 'demo-ad-paused',
    advertiserId: 'demo-advertiser',
    advertiserName: 'بوتيك الأناقة',
    advertiserEmail: 'boutique@example.com',
    categoryKey: 'clothing',
    title: 'إعلان متوقف مؤقتاً',
    description: 'تم إيقافه من لوحة الأدمن',
    images: [
      'https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=800&q=80&auto=format&fit=crop',
    ],
    placementId: 'agents_page_banner',
    durationDays: 14,
    pricePerDay: 9,
    totalAmount: 126,
    amountPaid: 126,
    isPaid: true,
    status: 'paused',
    rejectionReason: null,
    adminNotes: 'متوقف بطلب المعلن',
    fields: {
      whatsapp: '+963993153333',
      price: 75,
      shipping: 'pickup',
      sizes: ['m', 'l'],
      stockRemaining: 15,
    },
    startsAt: ISO,
    expiresAt: daysFromNow(10),
    views: 40,
    clicks: 3,
    createdAt: ISO,
    updatedAt: ISO,
  }),
  demoBase({
    id: 'demo-ad-rejected',
    advertiserId: 'demo-advertiser-3',
    advertiserName: 'أزياء الشرق',
    advertiserEmail: 'east@example.com',
    categoryKey: 'clothing',
    title: 'عرض مرفوض — صور غير واضحة',
    description: 'تم رفضه لعدم اكتمال الصور والوصف.',
    images: [],
    placementId: 'search_sidebar',
    durationDays: 7,
    pricePerDay: 8,
    totalAmount: 56,
    amountPaid: 56,
    isPaid: true,
    status: 'rejected',
    rejectionReason: 'الصور غير واضحة والوصف ناقص — يرجى إعادة التقديم.',
    fields: {
      sizes: ['m'],
      stockRemaining: 5,
      price: 60,
      whatsapp: '+963993153333',
      shipping: 'paid',
    },
    startsAt: null,
    expiresAt: null,
    views: 0,
    createdAt: ISO,
    updatedAt: ISO,
  }),
  demoBase({
    id: 'demo-ad-expired',
    advertiserId: 'demo-advertiser-4',
    advertiserName: 'ستايل دينيم',
    advertiserEmail: 'denim@example.com',
    categoryKey: 'clothing',
    title: 'حملة انتهت — تخفيضات الربيع',
    description: 'إعلان منتهي المدة (للتجربة في لوحة المنشورة).',
    images: [
      'https://images.unsplash.com/photo-1479064555552-3ef4979f8908?w=800&q=80&auto=format&fit=crop',
    ],
    placementId: 'home_featured_grid',
    durationDays: 7,
    pricePerDay: 15,
    totalAmount: 105,
    amountPaid: 105,
    isPaid: true,
    status: 'expired',
    rejectionReason: null,
    fields: {
      fabricTypes: ['denim'],
      colors: ['blue'],
      sizes: ['m', 'l'],
      stockRemaining: 0,
      price: 50,
      whatsapp: '+963993153333',
      discountPercent: 40,
      shipping: 'free',
    },
    startsAt: new Date(Date.now() - 14 * 86400000).toISOString(),
    expiresAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    views: 520,
    clicks: 61,
    createdAt: new Date(Date.now() - 14 * 86400000).toISOString(),
    updatedAt: ISO,
  }),
  demoBase({
    id: 'demo-ad-draft',
    advertiserId: 'demo-advertiser-2',
    advertiserName: 'متجر النخبة',
    advertiserEmail: 'elite@example.com',
    categoryKey: 'clothing',
    title: 'مسودة — معاطف مطر',
    description: 'لم يُرسل بعد للمراجعة.',
    images: [
      'https://images.unsplash.com/photo-1548126032-079a0fb0099d?w=800&q=80&auto=format&fit=crop',
    ],
    placementId: 'property_detail_sidebar',
    durationDays: 14,
    pricePerDay: 10,
    totalAmount: 140,
    amountPaid: 0,
    isPaid: false,
    status: 'draft',
    rejectionReason: null,
    fields: {
      fabricTypes: ['polyester'],
      colors: ['green', 'black'],
      sizes: ['m', 'l', 'xl'],
      stockRemaining: 20,
      price: 130,
      whatsapp: '+963993153333',
      shipping: 'paid',
    },
    startsAt: null,
    expiresAt: null,
    views: 0,
    createdAt: ISO,
    updatedAt: ISO,
  }),
];
