export const DEFAULT_NEWS_ITEMS = [
  {
    contentByLocale: {
      ar: 'أطلقت CIAR أداة تقييم عقاري بالذكاء الاصطناعي في أكثر من 60 دولة',
      en: 'CIAR launches new AI-powered property valuation tool across 60 countries',
      fr: "CIAR lance un outil d'évaluation immobilière par IA dans plus de 60 pays",
      es: 'CIAR lanza herramienta de valoración inmobiliaria con IA en más de 60 países',
      tr: "CIAR, 60'tan fazla ülkede yapay zekâ destekli değerleme aracını başlattı",
    },
    type: 'promo',
    order: 0,
  },
  {
    contentByLocale: {
      ar: 'سوق دبي العقاري يسجّل نمواً بنسبة 15% في الربع الأول من 2025',
      en: 'Dubai real estate market records 15% growth in Q1 2025',
      fr: 'Le marché immobilier de Dubaï enregistre une croissance de 15 % au T1 2025',
      es: 'El mercado inmobiliario de Dubái registra un crecimiento del 15 % en el primer trimestre de 2025',
      tr: "Dubai gayrimenkul piyasası 2025'in ilk çeyreğinde %15 büyüme kaydetti",
    },
    type: 'info',
    order: 1,
  },
  {
    contentByLocale: {
      ar: 'فلل فاخرة جديدة متاحة في الرياض وجدة',
      en: 'New luxury villa listings available in Riyadh and Jeddah',
      fr: 'Nouvelles villas de luxe disponibles à Riyad et Djeddah',
      es: 'Nuevas villas de lujo disponibles en Riad y Yeda',
      tr: "Riyad ve Cidde'de yeni lüks villa ilanları",
    },
    type: 'info',
    order: 2,
  },
  {
    contentByLocale: {
      ar: 'CIAR تدعم الآن الدفع الآمن عبر عدة طرق',
      en: 'CIAR now supports secure online payments via multiple methods',
      fr: 'CIAR prend désormais en charge les paiements en ligne sécurisés',
      es: 'CIAR ahora admite pagos en línea seguros con varios métodos',
      tr: 'CIAR artık birden fazla yöntemle güvenli çevrimiçi ödemeyi destekliyor',
    },
    type: 'promo',
    order: 3,
  },
  {
    contentByLocale: {
      ar: 'المغرب وجهة استثمارية رائدة لعام 2025',
      en: 'Morocco emerging as top investment destination for 2025',
      fr: "Le Maroc devient une destination d'investissement de premier plan en 2025",
      es: 'Marruecos emerge como principal destino de inversión en 2025',
      tr: 'Fas, 2025 için önde gelen yatırım destinasyonu olarak öne çıkıyor',
    },
    type: 'info',
    order: 4,
  },
] as const;

/** Static news rows when Firestore is unavailable (Netlify without env, quota, etc.). */
export function getDefaultNewsForApi() {
  const now = new Date().toISOString();
  return DEFAULT_NEWS_ITEMS.map((item, index) => ({
    id: `demo-news-${index}`,
    content: item.contentByLocale.ar,
    contentByLocale: item.contentByLocale,
    link: null,
    type: item.type,
    isActive: true,
    order: item.order,
    createdAt: now,
    updatedAt: now,
  }));
}

export const DEFAULT_FEATURES = [
  {
    key: 'ai_chatbot',
    name: 'AI Smart Chatbot',
    description: 'Conversational AI assistant for customer support and guidance',
    category: 'ai',
    icon: 'MessageCircle',
    order: 0,
  },
  {
    key: 'ai_recommendations',
    name: 'AI Recommendations',
    description: 'Personalized similar property recommendations',
    category: 'ai',
    icon: 'Sparkles',
    order: 0,
  },
  {
    key: 'ai_sentiment',
    name: 'AI Sentiment Analysis',
    description: 'Analyze review and listing text sentiment',
    category: 'ai',
    icon: 'Heart',
    order: 0,
  },
  {
    key: 'ai_seo',
    name: 'AI SEO Keywords',
    description: 'Suggest SEO keywords and meta descriptions for listings and ads',
    category: 'ai',
    icon: 'Search',
    order: 0,
  },
  {
    key: 'ai_inventory',
    name: 'AI Inventory Forecast',
    description: 'Predict ad stock demand and reorder suggestions',
    category: 'ai',
    icon: 'Package',
    order: 0,
  },
  {
    key: 'ai_fraud',
    name: 'AI Fraud Detection',
    description: 'Risk scoring for checkout payments and booking anomalies',
    category: 'ai',
    icon: 'Shield',
    order: 0,
  },
  {
    key: 'ai_ad_targeting',
    name: 'AI Ad Targeting',
    description: 'Suggest best ad placements and campaign tips for advertisers',
    category: 'ai',
    icon: 'Target',
    order: 0,
  },
  {
    key: 'ai_valuation',
    name: 'AI Property Valuation',
    description: 'AI-powered property value estimation based on market data',
    category: 'ai',
    icon: 'Brain',
    order: 1,
  },
  {
    key: 'virtual_tour',
    name: 'Virtual Tour Viewer',
    description: '360 panoramic virtual property tours',
    category: 'tools',
    icon: 'Eye',
    order: 2,
  },
  {
    key: 'roi_calculator',
    name: 'Investment ROI Calculator',
    description: 'Calculate return on investment for any property',
    category: 'analytics',
    icon: 'TrendingUp',
    order: 3,
  },
  {
    key: 'neighborhood',
    name: 'Neighborhood Insights',
    description: 'Detailed area analysis with safety, schools, and amenities',
    category: 'analytics',
    icon: 'MapPin',
    order: 4,
  },
  {
    key: 'walkability',
    name: 'Walkability and Transit Score',
    description: 'Walk score and public transit accessibility rating',
    category: 'analytics',
    icon: 'Footprints',
    order: 5,
  },
  {
    key: 'price_trends',
    name: 'Price Trend Analysis',
    description: 'Historical price data with interactive charts',
    category: 'analytics',
    icon: 'BarChart3',
    order: 6,
  },
  {
    key: 'price_alerts',
    name: 'Smart Price Alerts',
    description: 'Get notified when property prices drop',
    category: 'tools',
    icon: 'Bell',
    order: 7,
  },
  {
    key: 'reviews',
    name: 'Property Reviews',
    description: 'User reviews and ratings for properties',
    category: 'social',
    icon: 'Star',
    order: 8,
  },
  {
    key: 'floor_plan',
    name: 'Floor Plan Viewer',
    description: 'Interactive property floor plans',
    category: 'tools',
    icon: 'LayoutGrid',
    order: 9,
  },
  {
    key: 'heatmap',
    name: 'Price Heatmap',
    description: 'Visual price heatmap by area',
    category: 'analytics',
    icon: 'Flame',
    order: 10,
  },
  {
    key: 'schools',
    name: 'School District Ratings',
    description: 'Nearby school quality ratings',
    category: 'analytics',
    icon: 'GraduationCap',
    order: 11,
  },
  {
    key: 'commute',
    name: 'Commute Calculator',
    description: 'Estimate commute times to major hubs',
    category: 'tools',
    icon: 'Car',
    order: 12,
  },
  {
    key: 'carbon',
    name: 'Carbon Footprint Rating',
    description: 'Environmental impact and eco rating',
    category: 'analytics',
    icon: 'Leaf',
    order: 13,
  },
  {
    key: 'smart_home',
    name: 'Smart Home Compatibility',
    description: 'IoT and smart home device compatibility',
    category: 'tools',
    icon: 'Wifi',
    order: 14,
  },
  {
    key: 'noise',
    name: 'Noise Level Assessment',
    description: 'Environmental noise level analysis',
    category: 'analytics',
    icon: 'Volume2',
    order: 15,
  },
  {
    key: 'pet_friendly',
    name: 'Pet Friendliness Score',
    description: 'Pet-friendly amenities and policies',
    category: 'tools',
    icon: 'Dog',
    order: 16,
  },
  {
    key: 'nightlife',
    name: 'Nightlife Proximity',
    description: 'Entertainment and nightlife nearby',
    category: 'analytics',
    icon: 'Music',
    order: 17,
  },
  {
    key: 'seasonal',
    name: 'Seasonal Pricing',
    description: 'Price trends and analysis by season',
    category: 'analytics',
    icon: 'CalendarDays',
    order: 18,
  },
  {
    key: 'renovation',
    name: 'Renovation Estimator',
    description: 'Estimate renovation and improvement costs',
    category: 'tools',
    icon: 'Hammer',
    order: 19,
  },
  {
    key: 'rental_yield',
    name: 'Rental Yield Calculator',
    description: 'Calculate potential rental ROI',
    category: 'analytics',
    icon: 'Coin',
    order: 20,
  },
  {
    key: 'lifestyle',
    name: 'Lifestyle Match',
    description: 'AI-powered lifestyle preference matching',
    category: 'ai',
    icon: 'Heart',
    order: 21,
  },
  {
    key: 'disaster',
    name: 'Disaster Risk Assessment',
    description: 'Natural disaster risk evaluation',
    category: 'analytics',
    icon: 'ShieldAlert',
    order: 22,
  },
  {
    key: 'accessibility',
    name: 'Accessibility Score',
    description: 'Accessibility rating for disabled persons',
    category: 'tools',
    icon: 'Accessibility',
    order: 23,
  },
  {
    key: 'family',
    name: 'Family Friendliness',
    description: 'Family-oriented amenities score',
    category: 'analytics',
    icon: 'Users',
    order: 24,
  },
  {
    key: 'grocery',
    name: 'Grocery and Delivery',
    description: 'Nearby grocery and delivery coverage',
    category: 'tools',
    icon: 'ShoppingCart',
    order: 25,
  },
  {
    key: 'similarity',
    name: 'Similar Properties',
    description: 'Find properties similar to current one',
    category: 'tools',
    icon: 'Copy',
    order: 26,
  },
  {
    key: 'timeline',
    name: 'Property History',
    description: 'Track price and status changes over time',
    category: 'analytics',
    icon: 'History',
    order: 27,
  },
  {
    key: 'benchmark',
    name: 'Market Benchmark',
    description: 'Compare property against market averages',
    category: 'analytics',
    icon: 'Gauge',
    order: 28,
  },
  {
    key: 'energy',
    name: 'Energy Efficiency',
    description: 'Energy performance rating and costs',
    category: 'analytics',
    icon: 'Zap',
    order: 29,
  },
  {
    key: 'gamification',
    name: 'Gamified Exploration',
    description: 'Earn points and badges while exploring',
    category: 'general',
    icon: 'Trophy',
    order: 30,
  },
] as const;
